---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build release
    image: plugins/docker
    environment:
      ARCH: amd64
    settings:
      auto_tag: true
      auto_tag_suffix: amd64
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker
    environment:
      ARCH: amd64
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker
    environment:
      ARCH: amd64
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm64

steps:
  - name: build release
    image: plugins/docker:linux-arm
    environment:
      ARCH: arm
    settings:
      build_args_from_env:
        - ARCH
      auto_tag: true
      auto_tag_suffix: arm
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker:linux-arm
    environment:
      ARCH: arm
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker:linux-arm
    environment:
      ARCH: arm
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build release
    image: plugins/docker:linux-arm64
    environment:
      ARCH: arm64
    settings:
      auto_tag: true
      auto_tag_suffix: arm64
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker:linux-arm64
    environment:
      ARCH: arm64
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker:linux-arm64
    environment:
      ARCH: arm64
    settings:
      build_args_from_env:
        - ARCH
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: manifest

steps:
  - name: manifest
    image: plugins/manifest:1
    settings:
      spec: manifest.tmpl
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64
    when:
      event:
        exclude:
          - pull_request

depends_on:
  - amd64
  - arm
  - arm64
---
kind: signature
hmac: f23d1fbbfca201d3c980ba0388ada4a761375bef234ba409cddadf31f8f07ac8

...
