---
kind: pipeline
name: release

steps:
  - name: build & push release
    image: thegeeklab/drone-docker-buildx:20.11@sha256:327b6fb15dc841cf80c7c429f60d695efd7c7a476fe363afac25a58befd4c203
    settings:
      auto_tag: true
      repo: mazzolino/restic
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request

---
kind: pipeline
name: pr

steps:
  - name: build & push PR
    image: thegeeklab/drone-docker-buildx:20.11@sha256:327b6fb15dc841cf80c7c429f60d695efd7c7a476fe363afac25a58befd4c203
    settings:
      repo: mazzolino/restic
      tags:
        - pr-${DRONE_PULL_REQUEST}
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - pull_request

---
kind: signature
hmac: 979eb024a97a0673a421c496f9442193b3cbb401abdcd649a1d93e495b86601f

...
