---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build release
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: amd64
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm64

steps:
  - name: build release
    image: plugins/docker:linux-arm
    settings:
      auto_tag: true
      auto_tag_suffix: arm
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build release
    image: plugins/docker:linux-arm64
    settings:
      auto_tag: true
      auto_tag_suffix: arm64
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        include:
          - refs/heads/master
          - refs/tags/*

  - name: build branch
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: ${DRONE_BRANCH}-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

  - name: build pr
    image: plugins/docker
    settings:
      repo: mazzolino/restic-test
      tags: pr-${DRONE_PULL_REQUEST}-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - pull_request

---
kind: pipeline
name: manifest

steps:
  - name: manifest
    image: plugins/manifest:1
    settings:
      spec: manifest.tmpl
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64
    when:
      event:
        exclude:
          - pull_request

depends_on:
  - amd64
  - arm
  - arm64
---
kind: signature
hmac: 00c04a0ea2e5ca2a4df1df24a46dc70f391642ab7a4814de3cb2077d06c6d2e2

...
