kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build & push
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: amd64
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      repo:
        - djmaze/resticker
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: build
    image: plugins/docker
    settings:
      repo: mazzolino/restic
      dry_run: true
    when:
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm64

steps:
  - name: build & push
    image: plugins/docker:linux-arm
    settings:
      auto_tag: true
      auto_tag_suffix: arm
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      repo:
        - djmaze/resticker
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: build
    image: plugins/docker:linux-arm
    settings:
      repo: mazzolino/restic
      dry_run: true
    when:
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build & push
    image: plugins/docker:linux-arm64
    settings:
      auto_tag: true
      auto_tag_suffix: arm64
      repo: mazzolino/restic
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      repo:
        - djmaze/resticker
      ref:
        - refs/heads/master
        - refs/tags/*

  - name: build
    image: plugins/docker:linux-arm64
    settings:
      repo: mazzolino/restic
      dry_run: true
    when:
      ref:
        exclude:
          - refs/heads/master
          - refs/tags/*

---
kind: pipeline
name: manifest

steps:
  - name: manifest
    image: plugins/manifest:1
    settings:
      spec: manifest.tmpl
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64

depends_on:
  - amd64
  - arm
  - arm64
